events {}

http {
    upstream taskmind_api {
        server api:8000;
    }

    upstream notification_service {
        server notification-service:8001;
    }

    server {
        listen 80;

        location /notifications {
            proxy_pass http://notification_service;
        }

        location / {
            proxy_pass http://taskmind_api;
        }
    }
}
